import { Inter } from "next/font/google";
import './styles/globals.css';
import { Container, Grid } from '@mui/material';
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Apar Mistry",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
         <Container sx={{ padding: '2rem' }}>
          <Grid container spacing={2}>
            {children}
          </Grid>
        </Container>
      </body>
    
    </html>
  );
}

